services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      secrets:
        - npmrc
    container_name: kindergarten-scheduler
    ports:
      - "3100:3100"
    volumes:
      - scheduler-data:/app/data
    restart: unless-stopped

secrets:
  npmrc:
    file: ${USERPROFILE}/.npmrc

volumes:
  scheduler-data:
